// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SubjectTeacher.Data;

#nullable disable

namespace SubjectTeacher.Migrations
{
    [DbContext(typeof(SubjectTeacherContext))]
    partial class SubjectTeacherContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SubjectTeacher.Models.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectId"), 1L, 1);

                    b.Property<int>("SubjectCredits")
                        .HasColumnType("int");

                    b.Property<string>("SubjectTerm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SunbjectName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubjectId");

                    b.ToTable("Subject");
                });

            modelBuilder.Entity("SubjectTeacher.Models.Teacher", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherId"), 1L, 1);

                    b.Property<string>("TeacherAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeacherAge")
                        .HasColumnType("int");

                    b.Property<string>("TeacherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeacherSubjectsSubjectId")
                        .HasColumnType("int");

                    b.HasKey("TeacherId");

                    b.HasIndex("TeacherSubjectsSubjectId");

                    b.ToTable("Teacher");
                });

            modelBuilder.Entity("SubjectTeacher.Models.Teacher", b =>
                {
                    b.HasOne("SubjectTeacher.Models.Subject", "TeacherSubjects")
                        .WithMany("SubjectTeachers")
                        .HasForeignKey("TeacherSubjectsSubjectId");

                    b.Navigation("TeacherSubjects");
                });

            modelBuilder.Entity("SubjectTeacher.Models.Subject", b =>
                {
                    b.Navigation("SubjectTeachers");
                });
#pragma warning restore 612, 618
        }
    }
}
